name: "Terrascan"
description: "Run Terrascan"

runs:
  using: "composite"
  steps:
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        config_path: ${{ github.action_path }}/config.toml