name: "Checkov"
description: "Run Checkov"
inputs:
  directory:
    description: "Directory where checkov will be executed"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: ${{ inputs.directory }}
        framework: terraform
        config_file: ${{ github.action_path }}/config.yml
        output_format: json
        quiet: true