name: "TFSec on Changed Files"
description: "Run TFSec"

runs:
  using: "composite"
  steps:
    - name: tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        format: json
        additional_args: --config-file ${{ github.action_path }}/config.yml
